### ISSUE TITLE
Tests should use a different config

### ISSUE THREAD

**Issue by livinskull** [gizmore/gdo6#4]
Tests should use a different application config. (maybe `protected/config-test.php`?)

As it is, they overwrite the database used for development, dropping all data along with it, really annoying to find out _after_ one started the test script

**Comment by gizmore** [comment]
Not that easy.
Also affected is the files/ folder.
Maybe the files/ folder could be made dynamic as well, so files_test/ and config_test.php would be used.

**Comment by gizmore** [comment]
This issue has been resolved in 6.10.1-r1045
The GDO_File::filesDir() will return 'files_test' in UnitTest environment.
Every occurance of the GDO_PATH.'files' has been replaced with the GDO_File::filesDir().

Thx for flying gdo6!
