### ISSUE TITLE
Information about caching in ORMs is biased (incorrect)

### ISSUE THREAD

**Issue by tehron** [gizmore/gdo6#7]
DOCS/GDO_CACHING.md:
> In all ORM I found, Entity::getById(1) does always return a fresh copy.

This information should be updated, because you were told a while ago, that at least [PonyORM](https://ponyorm.org/) doesn't do that: https://docs.ponyorm.org/transactions.html#db-session-cache

The caching in a db_session scope is an additional feature. If you want to have the same behavior as with GDO6, just use a global db_session.

**Comment by gizmore** [comment]
A note has been added:

I got told the idea is not new. For example PONY ORM also should have a single identity cache, but i could not confirm this yet.
